name: Sync main to develop

on:
  workflow_call:
    inputs:
        from_branch:
            description: 'The name of the trunk-branch, default: main'
            default: 'main'
            required: false
            type: string
        to_branch:
            description: 'The name of the develop-branch, default: develop'
            default: 'develop'
            required: false
            type: string

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Opening pull request
        id: pull
        uses: skarnl/sync-branches@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: ${{ inputs.from_branch }}
          TO_BRANCH: ${{ inputs.to_branch }}
          PULL_REQUEST_BODY: "Merge changes from `${{ inputs.from_branch }}` to `${{ inputs.to_branch }}`. \n\n ⚠️ Please be aware! **MERGE** this PR, no _rebase_ - otherwise semantic versioning can become screwed!!!"

          # the PR-url is accessible with ${{jobs.pull.outputs.PULL_REQUEST_URL}}
          # optionally we could add Slack integration
